# Generated by Django 5.0.1 on 2024-03-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
    ]
