# Generated by Django 5.0.1 on 2024-03-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_product_remove_car_tags_remove_cartitems_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[(1, 'Toyota'), (2, 'ford'), (3, 'BMW'), (4, 'Mercedes')], max_length=50, verbose_name='Brand'),
        ),
    ]
