# Generated by Django 5.0.1 on 2024-03-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_product_name_alter_product_pimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pimage',
            new_name='product_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pdetails',
        ),
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(default=1, verbose_name='Product Details'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.IntegerField(choices=[(1, 'Toyota'), (2, 'ford'), (3, 'BMW'), (4, 'Mercedes')], verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
