# Generated by Django 5.0.1 on 2024-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_rename_is_active_product_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='carimage',
            field=models.ImageField(default=1, upload_to='carimage/', verbose_name='carimage'),
            preserve_default=False,
        ),
    ]
