# Generated by Django 5.0.1 on 2024-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0009_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[('Toyota', 'Toyota'), ('ford', 'ford'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes')], verbose_name='Category'),
        ),
    ]
