# Generated by Django 5.0.1 on 2024-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0010_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Toyota'), (2, 'ford'), (3, 'BMW'), (4, 'Mercedes')], verbose_name='Category'),
        ),
    ]
