# Generated by Django 5.0.1 on 2024-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0011_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.IntegerField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz')], default=1, verbose_name='Brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], verbose_name='Category'),
        ),
    ]
