# Generated by Django 5.0.1 on 2024-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0012_product_brand_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz')], max_length=50, verbose_name='Brand'),
        ),
    ]
