# Generated by Django 5.0.1 on 2024-03-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0013_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], max_length=50, verbose_name='Category'),
        ),
    ]
