# Generated by Django 5.0.1 on 2024-03-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0015_alter_product_brand_alter_product_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.IntegerField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz')], verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdetails',
            field=models.CharField(max_length=1000, verbose_name='Product Details'),
        ),
    ]
