# Generated by Django 5.0.1 on 2024-03-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0016_alter_product_brand_alter_product_cat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'toyota'), ('BMW', 'bmw'), ('MERCEDES', 'Mercedes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'SUV'), (2, 'Sedan'), (3, 'Hatchback')], verbose_name='Category'),
        ),
    ]
