# Generated by Django 5.0.1 on 2024-03-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0017_alter_product_brand_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('BMW', 'BMW'), ('MERCEDES', 'Mercedes')], max_length=50),
        ),
    ]
