# Generated by Django 5.0.1 on 2024-03-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0024_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
