# Generated by Django 5.0.1 on 2024-03-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0025_remove_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[(1, 'SUV'), (2, 'Sedan'), (3, 'Hatchback')], max_length=50, verbose_name='Category'),
        ),
    ]
