# Generated by Django 5.0.1 on 2024-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0026_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'SUV'), (2, 'Sedan'), (3, 'Hatchback')], verbose_name='Category'),
        ),
    ]
